--inserting data into table groups
INSERT INTO public.groups (id, title, description, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by) VALUES (1, 'Spring Boot Microservices 2021', 'description for Spring Boot', '2024-02-26 15:53:36.800832', NULL, '2024-02-26 15:53:36.800832', NULL, NULL, NULL);
INSERT INTO public.groups (id, title, description, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by) VALUES (3, 'Java Basics 2024', 'Basisc for Java development', '2024-02-26 16:00:39.506846', NULL, '2024-02-26 16:00:39.506846', NULL, NULL, NULL);
INSERT INTO public.groups (id, title, description, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by) VALUES (4, '.NET development', 'Learn fundamentals for .NET development', '2024-02-27 14:36:43.427753', NULL, '2024-02-27 14:36:43.427753', NULL, NULL, NULL);

--inserting data into instructors table
INSERT INTO public.instructors (id, first_name, last_name, email, bio, profile_picture, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by) VALUES (3, 'Qendrim', 'Pllana', 'qendrim@zgs.org', 'Cloud Engineer', NULL, '2024-02-29 00:54:21.849527', NULL, '2024-02-29 00:54:21.849527', NULL, NULL, NULL);
INSERT INTO public.instructors (id, first_name, last_name, email, bio, profile_picture, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by) VALUES (4, 'Arton', 'Bilalli', 'arton@zgs.org', 'Junior Software Engineer', NULL, '2024-02-29 00:58:13.165415', NULL, '2024-02-29 00:58:13.165415', NULL, NULL, NULL);
INSERT INTO public.instructors (id, first_name, last_name, email, bio, profile_picture, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by) VALUES (5, 'Jor', 'Pllana', 'jorpllana@zgs.org', '.NET Developer', NULL, '2024-02-29 00:59:59.743402', NULL, '2024-03-03 22:18:48.829233', NULL, NULL, NULL);

--inserting data into table students
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (1, 'Arton', 'Bilalli', 'ab@gmail.com', '+38163652153', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (8, 'Qendrim', 'Pllana', 'qp@gmail.com', '+38363653', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (9, 'Fjoralba', 'Krasniqi', 'fk@gmail.com', '+38368888', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (11, 'Jor', 'Pllana', 'jp@gmail.com', '+38355994', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (12, 'Alban', 'Rexhepi', 'ar@gmail.com', '+38351114', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (13, 'Altin', 'Rexhepi', 'ar1@gmail.com', '+383511111', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (14, 'Enes', 'Lutfiu', 'el@gmail.com', '+38377777', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (15, 'Dijon', 'Bilalli', 'db@gmail.com', '+383884411', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (16, 'Lorik', 'Ibrahimi', 'li@gmail.com', '+383333471', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (17, 'Nehat', 'Ahmedi', 'na@gmail.com', '+383333471', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.students (id, first_name, last_name, email, phone_number, address, gender, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, profile_picture) VALUES (18, 'Eron', 'Kadriu', 'ek@gmail.com', '+383222221', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
